### ISSUE TITLE
wsl run err

### ISSUE THREAD

**Issue by cexll** [hyperf/box#57]
```
./box version

Fatal error: Uncaught TypeError: App\Config::getConfigContent(): Return value must be of type array, null returned in phar:///mnt/c/code/home/box/box/app/Config.php:33
Stack trace:
#0 phar:///mnt/c/code/home/box/box/app/Config.php(66): App\Config->getConfigContent()
#1 phar:///mnt/c/code/home/box/box/app/Config.php(28): App\Config->init()
#2 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ObjectResolver.php(84): App\Config->__construct()
#3 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ObjectResolver.php(51): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#4 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(50): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#5 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/DepthGuard.php(67): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#6 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(51): Hyperf\Di\Resolver\DepthGuard->call('App\\Config', Object(Closure))
#7 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(186): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#8 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(71): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#9 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(116): Hyperf\Di\Container->make('App\\Config')
#10 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Aop/RegisterInjectPropertyHandler.php(40): Hyperf\Di\Container->get('App\\Config')
#11 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Aop/PropertyHandlerTrait.php(88): Hyperf\Di\Aop\RegisterInjectPropertyHandler::Hyperf\Di\Aop\{closure}(Object(App\DownloadManager), 'App\\DownloadMan...', 'App\\DownloadMan...', 'config', Object(Hyperf\Di\Annotation\Inject))
#12 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Aop/PropertyHandlerTrait.php(29): App\DownloadManager->__handle('App\\DownloadMan...', 'App\\DownloadMan...', Array)
#13 phar:///mnt/c/code/home/box/box/runtime/container/proxy/App_DownloadManager.proxy.php(33): App\DownloadManager->__handlePropertyHandler('App\\DownloadMan...')
#14 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ObjectResolver.php(84): App\DownloadManager->__construct()
#15 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ObjectResolver.php(51): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#16 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(50): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#17 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/DepthGuard.php(67): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#18 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(51): Hyperf\Di\Resolver\DepthGuard->call('App\\DownloadMan...', Object(Closure))
#19 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(186): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#20 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(71): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#21 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(116): Hyperf\Di\Container->make('App\\DownloadMan...')
#22 phar:///mnt/c/code/home/box/box/app/Command/GetCommand.php(33): Hyperf\Di\Container->get('App\\DownloadMan...')
#23 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ObjectResolver.php(84): App\Command\GetCommand->__construct(Object(Hyperf\Di\Container))
#24 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ObjectResolver.php(51): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#25 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(50): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#26 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/DepthGuard.php(67): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#27 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(51): Hyperf\Di\Resolver\DepthGuard->call('App\\Command\\Get...', Object(Closure))
#28 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(186): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#29 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(71): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#30 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(116): Hyperf\Di\Container->make('App\\Command\\Get...')
#31 phar:///mnt/c/code/home/box/box/vendor/hyperf/framework/src/ApplicationFactory.php(48): Hyperf\Di\Container->get('App\\Command\\Get...')
#32 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/FactoryResolver.php(45): Hyperf\Framework\ApplicationFactory->__invoke(Object(Hyperf\Di\Container))
#33 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(50): Hyperf\Di\Resolver\FactoryResolver->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#34 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/DepthGuard.php(67): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#35 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(51): Hyperf\Di\Resolver\DepthGuard->call('Hyperf\\Contract...', Object(Closure))
#36 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(186): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#37 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(71): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#38 phar:///mnt/c/code/home/box/box/vendor/hyperf/di/src/Container.php(116): Hyperf\Di\Container->make('Hyperf\\Contract...')
#39 phar:///mnt/c/code/home/box/box/bin/hyperf.php(49): Hyperf\Di\Container->get('Hyperf\\Contract...')
#40 phar:///mnt/c/code/home/box/box/bin/hyperf.php(51): {closure}()
#41 /mnt/c/code/home/box/box(10): include('phar:///mnt/c/c...')
#42 {main}
  thrown in phar:///mnt/c/code/home/box/box/app/Config.php on line 33
```

**Comment by cexll** [comment]
wsl2 没问题
